services:
  - type: web
    name: velixa-backend
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DOWNLOADS_DIR
        value: downloads
