import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: "#121212",
  },
  introOverlay: {
    position: "absolute",
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
    zIndex: 50,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#040605",
    paddingHorizontal: 24,
  },
  introSimpleWordmark: {
    color: "#ffffff",
    fontSize: 44,
    lineHeight: 48,
    fontWeight: "900",
    letterSpacing: -1.2,
  },
  scrollContent: {
    paddingHorizontal: 16,
    paddingTop: 26,
    paddingBottom: 208,
    gap: 18,
  },
  screenHeaderRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  profileBadge: {
    width: 38,
    height: 38,
    borderRadius: 999,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#1db954",
  },
  profileBadgeText: {
    color: "#041208",
    fontSize: 15,
    fontWeight: "800",
  },
  filterPillRow: {
    gap: 8,
    paddingRight: 8,
  },
  filterPill: {
    borderRadius: 999,
    backgroundColor: "#242424",
    paddingHorizontal: 14,
    paddingVertical: 10,
  },
  filterPillActive: {
    backgroundColor: "#1ed760",
  },
  filterPillText: {
    color: "#f3f4f6",
    fontSize: 12,
    fontWeight: "700",
  },
  filterPillTextActive: {
    color: "#041208",
  },
  screenTitle: {
    color: "#ffffff",
    fontSize: 30,
    lineHeight: 34,
    fontWeight: "800",
    letterSpacing: -0.8,
  },
  screenSubtitle: {
    marginTop: 6,
    color: "#a3a7ad",
    fontSize: 14,
    lineHeight: 21,
  },
  mediaShortcutGrid: {
    marginTop: 16,
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
  },
  mediaShortcutTile: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    width: "48%",
    borderRadius: 14,
    backgroundColor: "#232323",
    overflow: "hidden",
    minHeight: 72,
    paddingRight: 10,
  },
  mediaShortcutArtwork: {
    width: 72,
    height: 72,
    backgroundColor: "#1b1b1b",
  },
  mediaShortcutFallback: {
    width: 72,
    height: 72,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#1ed760",
  },
  mediaShortcutFallbackText: {
    color: "#041208",
    fontSize: 18,
    fontWeight: "900",
  },
  mediaShortcutCopy: {
    flex: 1,
    minWidth: 0,
  },
  mediaShortcutTitle: {
    color: "#ffffff",
    fontSize: 13,
    fontWeight: "800",
  },
  mediaShortcutSubtitle: {
    marginTop: 4,
    color: "#acb0b5",
    fontSize: 11,
    lineHeight: 16,
  },
  featureStoryCard: {
    flexDirection: "row",
    borderRadius: 18,
    backgroundColor: "#2b2b2b",
    overflow: "hidden",
  },
  featureStoryArtwork: {
    width: 136,
    height: 136,
    backgroundColor: "#1b1b1b",
  },
  featureStoryFallback: {
    width: 136,
    height: 136,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#1ed760",
  },
  featureStoryFallbackText: {
    color: "#041208",
    fontSize: 16,
    fontWeight: "800",
    letterSpacing: 1.2,
  },
  featureStoryCopy: {
    flex: 1,
    paddingHorizontal: 14,
    paddingVertical: 14,
  },
  featureStoryTitle: {
    marginTop: 8,
    color: "#ffffff",
    fontSize: 18,
    lineHeight: 23,
    fontWeight: "800",
  },
  featureStorySubtitle: {
    marginTop: 8,
    color: "#bcc0c5",
    fontSize: 13,
    lineHeight: 19,
  },
  sectionListTitle: {
    color: "#ffffff",
    fontSize: 28,
    lineHeight: 32,
    fontWeight: "800",
    letterSpacing: -0.7,
  },
  searchBarWrap: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    borderRadius: 10,
    backgroundColor: "#ffffff",
    paddingHorizontal: 14,
    paddingVertical: 10,
  },
  searchBarIcon: {
    color: "#111111",
    fontSize: 18,
    fontWeight: "700",
  },
  searchBarInput: {
    flex: 1,
    color: "#111111",
    fontSize: 15,
    fontWeight: "600",
    paddingVertical: 2,
  },
  browseGrid: {
    marginTop: 12,
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
  },
  browseTile: {
    width: "48%",
    minHeight: 98,
    borderRadius: 10,
    paddingHorizontal: 14,
    paddingTop: 14,
    overflow: "hidden",
  },
  browseTileText: {
    color: "#ffffff",
    fontSize: 16,
    lineHeight: 21,
    fontWeight: "800",
  },
  browseTileAccent: {
    position: "absolute",
    right: -12,
    bottom: -10,
    width: 72,
    height: 72,
    borderRadius: 10,
    backgroundColor: "rgba(255,255,255,0.18)",
    transform: [{ rotate: "26deg" }],
  },
  browseTileBlue: { backgroundColor: "#5577d5" },
  browseTileOrange: { backgroundColor: "#e86c3c" },
  browseTileSky: { backgroundColor: "#65a8d8" },
  browseTileCyan: { backgroundColor: "#69add1" },
  browseTileRust: { backgroundColor: "#cc6635" },
  browseTilePurple: { backgroundColor: "#8f53b2" },
  browseTileIndigo: { backgroundColor: "#3956b0" },
  browseTileMagenta: { backgroundColor: "#8e53a8" },
  queueHeroCard: {
    borderRadius: 24,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.06)",
    backgroundColor: "#181818",
    padding: 18,
  },
  heroCard: {
    borderRadius: 28,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.06)",
    backgroundColor: "#181818",
    padding: 20,
    shadowColor: "#000000",
    shadowOpacity: 0.28,
    shadowRadius: 24,
    shadowOffset: { width: 0, height: 18 },
  },
  heroTopRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    gap: 12,
  },
  eyebrow: {
    color: "#9ea0a6",
    fontSize: 11,
    letterSpacing: 3,
    fontWeight: "700",
  },
  heroLabel: {
    marginTop: 6,
    color: "#f5f7f5",
    fontSize: 18,
    fontWeight: "600",
  },
  livePill: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.08)",
    backgroundColor: "#131313",
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  liveDot: {
    width: 8,
    height: 8,
    borderRadius: 999,
    backgroundColor: "#1ed760",
  },
  liveText: {
    color: "#d9dbde",
    fontSize: 13,
    fontWeight: "600",
  },
  heroTitle: {
    marginTop: 24,
    color: "#ffffff",
    fontSize: 38,
    lineHeight: 42,
    fontWeight: "800",
    letterSpacing: -1.5,
  },
  heroSubtitle: {
    marginTop: 14,
    maxWidth: 540,
    color: "#9ea0a6",
    fontSize: 15,
    lineHeight: 24,
  },
  metricsGrid: {
    marginTop: 20,
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
  },
  metricCard: {
    minWidth: "47%",
    flex: 1,
    borderRadius: 22,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.07)",
    backgroundColor: "#121212",
    paddingHorizontal: 14,
    paddingVertical: 16,
  },
  metricCardActive: {
    borderColor: "rgba(99,174,255,0.2)",
    backgroundColor: "#11161a",
  },
  metricLabel: {
    color: "#8f9299",
    fontSize: 11,
    letterSpacing: 2.5,
    textTransform: "uppercase",
    fontWeight: "700",
  },
  metricValue: {
    marginTop: 12,
    color: "#ffffff",
    fontSize: 32,
    lineHeight: 36,
    fontWeight: "800",
    textAlign: "center",
  },
  metricValueGreen: {
    color: "#1ed760",
  },
  metricValueBlue: {
    color: "#72b8ff",
  },
  metricValueRed: {
    color: "#ff7d8d",
  },
  sectionCard: {
    borderRadius: 24,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.06)",
    backgroundColor: "#181818",
    padding: 16,
  },
  sectionSwitch: {
    flexDirection: "row",
    gap: 10,
    padding: 6,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.08)",
    backgroundColor: "#0f0f0f",
  },
  sectionSwitchButton: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 999,
    paddingVertical: 14,
    paddingHorizontal: 14,
  },
  sectionSwitchButtonActive: {
    backgroundColor: "#1ed760",
  },
  sectionSwitchText: {
    color: "#c6c9cd",
    fontSize: 14,
    fontWeight: "700",
    letterSpacing: 0.2,
  },
  sectionSwitchTextActive: {
    color: "#041208",
  },
  bottomTabBar: {
    position: "absolute",
    left: 12,
    right: 12,
    bottom: 12,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 8,
    padding: 6,
    borderRadius: 24,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.06)",
    backgroundColor: "rgba(18,18,18,0.98)",
  },
  bottomTabButton: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    gap: 4,
    borderRadius: 18,
    paddingVertical: 10,
    paddingHorizontal: 8,
  },
  bottomTabButtonActive: {
    backgroundColor: "#2a2a2a",
  },
  bottomTabIcon: {
    color: "#8f9399",
    fontSize: 18,
    fontWeight: "700",
  },
  bottomTabIconActive: {
    color: "#ffffff",
  },
  bottomTabText: {
    color: "#a2a6ab",
    fontSize: 10,
    fontWeight: "700",
  },
  bottomTabTextActive: {
    color: "#ffffff",
  },
  sectionEyebrow: {
    color: "#1ed760",
    fontSize: 11,
    fontWeight: "700",
    letterSpacing: 2.6,
    textTransform: "uppercase",
  },
  sectionTitle: {
    marginTop: 10,
    color: "#ffffff",
    fontSize: 26,
    lineHeight: 30,
    fontWeight: "800",
    letterSpacing: -0.8,
  },
  sectionCopy: {
    marginTop: 10,
    color: "#9ea0a6",
    fontSize: 14,
    lineHeight: 22,
  },
  input: {
    marginTop: 14,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.06)",
    backgroundColor: "#121212",
    color: "#ffffff",
    paddingHorizontal: 16,
    paddingVertical: 16,
    fontSize: 15,
  },
  primaryButton: {
    marginTop: 14,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 999,
    backgroundColor: "#1db954",
    paddingHorizontal: 18,
    paddingVertical: 16,
  },
  primaryButtonText: {
    color: "#041208",
    fontSize: 15,
    fontWeight: "800",
    letterSpacing: 0.3,
    textTransform: "uppercase",
  },
  secondaryButton: {
    marginTop: 10,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 999,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.08)",
    backgroundColor: "#171717",
    paddingHorizontal: 18,
    paddingVertical: 15,
  },
  secondaryButtonCompact: {
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 999,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.08)",
    backgroundColor: "#171717",
    paddingHorizontal: 14,
    paddingVertical: 10,
  },
  secondaryButtonText: {
    color: "#f4f5f6",
    fontSize: 13,
    fontWeight: "700",
    letterSpacing: 0.2,
  },
  disabledButton: {
    opacity: 0.55,
  },
  apiHint: {
    marginTop: 12,
    color: "#7b7e84",
    fontSize: 12,
    lineHeight: 18,
  },
  errorCard: {
    borderRadius: 22,
    borderWidth: 1,
    borderColor: "rgba(255,125,141,0.18)",
    backgroundColor: "rgba(110,28,38,0.35)",
    padding: 16,
  },
  errorTitle: {
    color: "#ffd7dc",
    fontSize: 14,
    fontWeight: "700",
  },
  errorText: {
    marginTop: 6,
    color: "#ff9ba7",
    fontSize: 13,
    lineHeight: 20,
  },
  playlistHeader: {
    marginTop: 14,
    flexDirection: "row",
    gap: 14,
    alignItems: "center",
  },
  playlistImage: {
    width: 82,
    height: 82,
    borderRadius: 20,
    backgroundColor: "#1b1b1b",
  },
  playlistCopy: {
    flex: 1,
  },
  playlistTitle: {
    color: "#ffffff",
    fontSize: 20,
    lineHeight: 25,
    fontWeight: "800",
  },
  playlistMeta: {
    marginTop: 8,
    color: "#9ea0a6",
    fontSize: 14,
  },
  playerHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
  },
  playerModePill: {
    borderRadius: 999,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.08)",
    backgroundColor: "#171717",
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  playerModeText: {
    color: "#d2d5d8",
    fontSize: 12,
    fontWeight: "600",
  },
  emptyPlayer: {
    marginTop: 14,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.08)",
    borderStyle: "dashed",
    paddingHorizontal: 16,
    paddingVertical: 22,
  },
  emptyPlayerTitle: {
    color: "#ffffff",
    fontSize: 15,
    fontWeight: "700",
  },
  emptyPlayerText: {
    marginTop: 8,
    color: "#9ea0a6",
    fontSize: 13,
    lineHeight: 20,
  },
  nowPlayingTitle: {
    marginTop: 14,
    color: "#ffffff",
    fontSize: 18,
    lineHeight: 25,
    fontWeight: "800",
  },
  nowPlayingMeta: {
    marginTop: 6,
    color: "#9ea0a6",
    fontSize: 14,
  },
  libraryHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 12,
  },
  headerPills: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    justifyContent: "flex-end",
  },
  countPill: {
    borderRadius: 999,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.08)",
    backgroundColor: "#171717",
    paddingHorizontal: 12,
    paddingVertical: 9,
  },
  countPillText: {
    color: "#d9dbde",
    fontSize: 12,
    fontWeight: "600",
  },
  selectionActions: {
    marginTop: 16,
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
  },
  quickGrid: {
    marginTop: 16,
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
  },
  quickTile: {
    minWidth: "47%",
    flex: 1,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.08)",
    backgroundColor: "#171717",
    padding: 14,
  },
  quickTileTitle: {
    color: "#ffffff",
    fontSize: 15,
    fontWeight: "800",
  },
  quickTileCopy: {
    marginTop: 6,
    color: "#9ea0a6",
    fontSize: 12,
    lineHeight: 18,
  },
  songList: {
    marginTop: 14,
    gap: 10,
  },
  shelfRow: {
    paddingTop: 16,
    paddingRight: 6,
    gap: 12,
  },
  shelfCard: {
    width: 152,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.07)",
    backgroundColor: "#151c16",
    padding: 12,
  },
  shelfCardBlue: {
    backgroundColor: "#121923",
  },
  shelfArtwork: {
    width: "100%",
    height: 128,
    borderRadius: 14,
    backgroundColor: "#1b1b1b",
  },
  shelfFallback: {
    width: "100%",
    height: 128,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#17231b",
  },
  shelfFallbackBlue: {
    backgroundColor: "#172133",
  },
  shelfFallbackText: {
    color: "#1ed760",
    fontSize: 12,
    fontWeight: "800",
    letterSpacing: 1.4,
  },
  shelfTitle: {
    marginTop: 12,
    color: "#ffffff",
    fontSize: 14,
    lineHeight: 20,
    fontWeight: "800",
  },
  shelfSubtitle: {
    marginTop: 6,
    color: "#a2a6ab",
    fontSize: 12,
    lineHeight: 18,
  },
  songCard: {
    borderRadius: 20,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.06)",
    backgroundColor: "#181818",
    padding: 14,
  },
  songTopRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  songArtwork: {
    width: 54,
    height: 54,
    borderRadius: 8,
    backgroundColor: "#1b1b1b",
  },
  songArtworkFallback: {
    width: 54,
    height: 54,
    borderRadius: 8,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#6edb63",
  },
  songArtworkFallbackText: {
    color: "#06250e",
    fontSize: 15,
    fontWeight: "800",
  },
  checkboxWrap: {
    paddingVertical: 4,
  },
  checkbox: {
    width: 20,
    height: 20,
    borderRadius: 999,
    borderWidth: 1.5,
    borderColor: "rgba(255,255,255,0.22)",
    alignItems: "center",
    justifyContent: "center",
  },
  checkboxSelected: {
    borderColor: "#1ed760",
    backgroundColor: "rgba(30,215,96,0.12)",
  },
  checkboxDot: {
    width: 8,
    height: 8,
    borderRadius: 999,
    backgroundColor: "#1ed760",
  },
  songCopy: {
    flex: 1,
    minWidth: 0,
  },
  songTitle: {
    color: "#ffffff",
    fontSize: 15,
    fontWeight: "700",
  },
  songMeta: {
    marginTop: 4,
    color: "#9ea0a6",
    fontSize: 12,
  },
  statusPill: {
    borderRadius: 999,
    borderWidth: 1,
    paddingHorizontal: 10,
    paddingVertical: 7,
  },
  statusPending: {
    borderColor: "rgba(255,255,255,0.08)",
    backgroundColor: "#1a1a1a",
  },
  statusDownloading: {
    borderColor: "rgba(114,184,255,0.2)",
    backgroundColor: "rgba(114,184,255,0.08)",
  },
  statusCompleted: {
    borderColor: "rgba(30,215,96,0.18)",
    backgroundColor: "rgba(30,215,96,0.1)",
  },
  statusFailed: {
    borderColor: "rgba(255,125,141,0.18)",
    backgroundColor: "rgba(255,125,141,0.1)",
  },
  statusText: {
    color: "#d2d5d8",
    fontSize: 11,
    fontWeight: "700",
    textTransform: "capitalize",
  },
  statusTextGreen: {
    color: "#1ed760",
  },
  progressBlock: {
    marginTop: 12,
  },
  progressTrack: {
    height: 8,
    borderRadius: 999,
    backgroundColor: "#1d1d1d",
    overflow: "hidden",
  },
  progressFill: {
    height: "100%",
    borderRadius: 999,
    backgroundColor: "#1ed760",
  },
  songError: {
    marginTop: 8,
    color: "#ff9ba7",
    fontSize: 12,
    lineHeight: 18,
  },
  songActions: {
    marginTop: 12,
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  ghostButton: {
    borderRadius: 999,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.08)",
    backgroundColor: "#171717",
    paddingHorizontal: 14,
    paddingVertical: 10,
  },
  ghostButtonText: {
    color: "#f4f5f6",
    fontSize: 12,
    fontWeight: "700",
    textTransform: "uppercase",
  },
  retryButton: {
    borderRadius: 999,
    borderWidth: 1,
    borderColor: "rgba(255,125,141,0.18)",
    backgroundColor: "rgba(255,125,141,0.1)",
    paddingHorizontal: 14,
    paddingVertical: 10,
  },
  retryButtonText: {
    color: "#ff9ba7",
    fontSize: 12,
    fontWeight: "700",
    textTransform: "uppercase",
  },
  libraryMessageCard: {
    borderRadius: 22,
    borderWidth: 1,
    borderColor: "rgba(30,215,96,0.18)",
    backgroundColor: "rgba(18,72,39,0.35)",
    padding: 16,
  },
  libraryMessageTitle: {
    color: "#d9ffe9",
    fontSize: 14,
    fontWeight: "700",
  },
  libraryMessageText: {
    marginTop: 6,
    color: "#8df0b4",
    fontSize: 13,
    lineHeight: 20,
  },
  libraryHeroCard: {
    position: "relative",
    overflow: "hidden",
    borderRadius: 28,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.08)",
    backgroundColor: "#0f5f27",
    padding: 20,
  },
  libraryHeroGlow: {
    position: "absolute",
    top: -60,
    right: -40,
    width: 180,
    height: 180,
    borderRadius: 999,
    backgroundColor: "rgba(30,215,96,0.12)",
  },
  libraryHeroTitle: {
    marginTop: 10,
    color: "#ffffff",
    fontSize: 30,
    lineHeight: 35,
    fontWeight: "800",
    letterSpacing: -0.8,
  },
  libraryHeroArtwork: {
    width: 172,
    height: 172,
    alignSelf: "center",
    borderRadius: 10,
    marginBottom: 18,
    backgroundColor: "#1b1b1b",
  },
  libraryHeroArtworkFallback: {
    width: 172,
    height: 172,
    alignSelf: "center",
    borderRadius: 10,
    marginBottom: 18,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#72db63",
  },
  libraryHeroArtworkFallbackText: {
    color: "#06250e",
    fontSize: 18,
    fontWeight: "800",
    letterSpacing: 1.2,
  },
  libraryTopBar: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 4,
    marginBottom: 10,
  },
  libraryBackButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#171717",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.08)",
  },
  libraryBackIcon: {
    color: "#ffffff",
    fontSize: 18,
    fontWeight: "700",
  },
  libraryTopTitle: {
    color: "#ffffff",
    fontSize: 24,
    fontWeight: "800",
    letterSpacing: -0.4,
  },
  libraryTopBarSpacer: {
    width: 40,
    height: 40,
  },
  libraryControlsCard: {
    borderRadius: 20,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.08)",
    backgroundColor: "#111111",
    padding: 14,
  },
  libraryActionRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    marginBottom: 12,
  },
  libraryIconAction: {
    width: 42,
    height: 42,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.1)",
    backgroundColor: "#1a1a1a",
    alignItems: "center",
    justifyContent: "center",
  },
  libraryIconActionText: {
    color: "#d8dae0",
    fontSize: 17,
    fontWeight: "700",
  },
  libraryPlayMainWrap: {
    flex: 1,
    alignItems: "flex-end",
  },
  libraryPlayMainButton: {
    borderRadius: 999,
    backgroundColor: "#1ed760",
    minWidth: 94,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 18,
    paddingVertical: 11,
  },
  libraryPlayMainText: {
    color: "#041a0b",
    fontSize: 14,
    fontWeight: "800",
  },
  repairButton: {
    marginBottom: 12,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "rgba(30,215,96,0.28)",
    backgroundColor: "rgba(30,215,96,0.12)",
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 10,
  },
  repairButtonText: {
    color: "#1ed760",
    fontSize: 13,
    fontWeight: "800",
  },
  librarySearchInput: {
    borderRadius: 12,
    backgroundColor: "#1a1a1a",
    color: "#f5f6f7",
    paddingHorizontal: 14,
    paddingVertical: 12,
    fontSize: 14,
    fontWeight: "600",
  },
  libraryChipsRow: {
    marginTop: 12,
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  libraryChip: {
    borderRadius: 999,
    backgroundColor: "#1c1c1c",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.08)",
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  libraryChipActive: {
    backgroundColor: "rgba(30,215,96,0.18)",
    borderColor: "rgba(30,215,96,0.32)",
  },
  libraryChipText: {
    color: "#d1d3d8",
    fontSize: 12,
    fontWeight: "700",
  },
  libraryChipTextActive: {
    color: "#1ed760",
  },
  libraryListWrap: {
    marginTop: 12,
    gap: 8,
  },
  libraryListRow: {
    flexDirection: "row",
    alignItems: "center",
    borderRadius: 12,
    backgroundColor: "#0f0f0f",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.04)",
    paddingHorizontal: 10,
    paddingVertical: 8,
    gap: 10,
  },
  libraryListRowActive: {
    borderColor: "rgba(30,215,96,0.28)",
    backgroundColor: "#121813",
  },
  libraryListArtwork: {
    width: 54,
    height: 54,
    borderRadius: 6,
    backgroundColor: "#1b1b1b",
  },
  libraryListArtworkFallback: {
    width: 54,
    height: 54,
    borderRadius: 6,
    backgroundColor: "#1b1b1b",
    alignItems: "center",
    justifyContent: "center",
  },
  libraryListArtworkFallbackText: {
    color: "#1ed760",
    fontSize: 16,
    fontWeight: "800",
  },
  libraryListCopy: {
    flex: 1,
    minWidth: 0,
  },
  libraryListTitle: {
    color: "#f5f6f7",
    fontSize: 16,
    fontWeight: "700",
  },
  libraryListMeta: {
    marginTop: 4,
    color: "#a0a4aa",
    fontSize: 14,
  },
  libraryListRight: {
    alignItems: "flex-end",
    justifyContent: "center",
    gap: 6,
  },
  libraryListPlaying: {
    color: "#1ed760",
    fontSize: 11,
    fontWeight: "700",
  },
  libraryRowMenuButton: {
    width: 28,
    height: 28,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
  },
  libraryRowMenuText: {
    color: "#a8acb2",
    fontSize: 20,
    lineHeight: 20,
  },
  searchHeroCard: {
    borderRadius: 28,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.08)",
    backgroundColor: "#131313",
    padding: 20,
  },
  spotifySearchInput: {
    marginTop: 16,
    borderRadius: 999,
    backgroundColor: "#ffffff",
    color: "#0a0a0a",
    paddingHorizontal: 18,
    paddingVertical: 16,
    fontSize: 15,
    fontWeight: "600",
  },
  genreGrid: {
    marginTop: 16,
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
  },
  genreTile: {
    minWidth: "47%",
    flex: 1,
    borderRadius: 18,
    paddingHorizontal: 14,
    paddingVertical: 26,
  },
  genreTileGreen: {
    backgroundColor: "#1d6040",
  },
  genreTileOrange: {
    backgroundColor: "#a03d18",
  },
  genreTileBlue: {
    backgroundColor: "#215f9a",
  },
  genreTilePink: {
    backgroundColor: "#8b2b63",
  },
  genreTileText: {
    color: "#ffffff",
    fontSize: 18,
    fontWeight: "800",
    letterSpacing: -0.4,
  },
  libraryStatsRow: {
    marginTop: 18,
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
  },
  libraryStatPill: {
    flex: 1,
    minWidth: "30%",
    borderRadius: 18,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.08)",
    backgroundColor: "rgba(255,255,255,0.04)",
    paddingHorizontal: 14,
    paddingVertical: 14,
  },
  libraryStatValue: {
    color: "#ffffff",
    fontSize: 18,
    fontWeight: "800",
  },
  libraryStatLabel: {
    marginTop: 4,
    color: "#9ea0a6",
    fontSize: 12,
    fontWeight: "600",
  },
  primaryButtonCompact: {
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 999,
    backgroundColor: "#1ed760",
    paddingHorizontal: 18,
    paddingVertical: 12,
    minWidth: 112,
  },
  loopButtonActive: {
    borderColor: "rgba(30,215,96,0.24)",
    backgroundColor: "rgba(30,215,96,0.12)",
  },
  loopButtonTextActive: {
    color: "#1ed760",
  },
  libraryNowPlayingCard: {
    marginTop: 16,
    flexDirection: "row",
    alignItems: "center",
    gap: 14,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.08)",
    backgroundColor: "#151515",
    padding: 14,
  },
  libraryNowPlayingImage: {
    width: 78,
    height: 78,
    borderRadius: 18,
    backgroundColor: "#1b1b1b",
  },
  libraryNowPlayingFallback: {
    width: 78,
    height: 78,
    borderRadius: 18,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#1a1a1a",
  },
  libraryNowPlayingFallbackText: {
    color: "#1ed760",
    fontSize: 12,
    fontWeight: "800",
    letterSpacing: 1.4,
  },
  libraryNowPlayingCopy: {
    flex: 1,
    minWidth: 0,
  },
  playbackRail: {
    marginTop: 16,
    gap: 8,
  },
  playbackTimeRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  playbackTimeText: {
    color: "#9ea0a6",
    fontSize: 12,
    fontWeight: "600",
  },
  playerControlsRow: {
    marginTop: 16,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 10,
  },
  savedTrackCard: {
    borderRadius: 20,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.07)",
    backgroundColor: "#141414",
    padding: 14,
  },
  savedTrackCardActive: {
    borderColor: "rgba(30,215,96,0.22)",
    backgroundColor: "#111814",
  },
  savedTrackTopRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  savedTrackImage: {
    width: 60,
    height: 60,
    borderRadius: 16,
    backgroundColor: "#1b1b1b",
  },
  savedTrackPlaceholder: {
    width: 60,
    height: 60,
    borderRadius: 16,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#1b1b1b",
  },
  savedTrackPlaceholderText: {
    color: "#1ed760",
    fontSize: 10,
    fontWeight: "800",
    letterSpacing: 1.2,
  },
  savedTrackCopy: {
    flex: 1,
    minWidth: 0,
  },
  savedTrackTitle: {
    color: "#ffffff",
    fontSize: 15,
    lineHeight: 22,
    fontWeight: "800",
  },
  savedTrackMeta: {
    marginTop: 4,
    color: "#9ea0a6",
    fontSize: 13,
  },
  savedTrackHint: {
    marginTop: 6,
    color: "#7f8288",
    fontSize: 12,
    lineHeight: 18,
  },
  spotifyPlayerCard: {
    marginTop: 16,
    borderRadius: 26,
    overflow: "hidden",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.08)",
    backgroundColor: "#121212",
  },
  spotifyPlayerArtwork: {
    width: "100%",
    aspectRatio: 1,
    backgroundColor: "#181818",
  },
  spotifyPlayerFallback: {
    width: "100%",
    aspectRatio: 1,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#151515",
  },
  spotifyPlayerFallbackText: {
    color: "#1ed760",
    fontSize: 22,
    fontWeight: "800",
    letterSpacing: 2,
  },
  spotifyPlayerCopy: {
    paddingHorizontal: 18,
    paddingVertical: 18,
  },
  spotifyPlayerTitle: {
    color: "#ffffff",
    fontSize: 24,
    lineHeight: 29,
    fontWeight: "800",
  },
  spotifyPlayerArtist: {
    marginTop: 8,
    color: "#cfd2d6",
    fontSize: 15,
    fontWeight: "600",
  },
  spotifyControlRow: {
    marginTop: 18,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 10,
  },
  primaryPlayButton: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 999,
    backgroundColor: "#1ed760",
    paddingHorizontal: 20,
    paddingVertical: 16,
    minHeight: 56,
  },
  primaryPlayButtonText: {
    color: "#041208",
    fontSize: 16,
    fontWeight: "800",
    textTransform: "uppercase",
    letterSpacing: 0.3,
  },
  miniPlayerDock: {
    position: "absolute",
    left: 12,
    right: 12,
    bottom: 86,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.08)",
    backgroundColor: "#1f7a3f",
    padding: 10,
    gap: 10,
  },
  miniPlayerMain: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    flex: 1,
  },
  miniPlayerImage: {
    width: 46,
    height: 46,
    borderRadius: 8,
    backgroundColor: "#1b1b1b",
  },
  miniPlayerFallback: {
    width: 46,
    height: 46,
    borderRadius: 8,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#1b1b1b",
  },
  miniPlayerFallbackText: {
    color: "#1ed760",
    fontSize: 18,
    fontWeight: "800",
  },
  miniPlayerCopy: {
    flex: 1,
    minWidth: 0,
  },
  miniPlayerTitle: {
    color: "#ffffff",
    fontSize: 14,
    fontWeight: "700",
  },
  miniPlayerMeta: {
    marginTop: 4,
    color: "#9ea0a6",
    fontSize: 12,
  },
  miniPlayerActions: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-end",
    gap: 8,
  },
  miniPlayerIconButton: {
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 999,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.08)",
    backgroundColor: "rgba(0,0,0,0.18)",
    width: 36,
    height: 36,
  },
  miniPlayerIconText: {
    color: "#f4f5f6",
    fontSize: 13,
    fontWeight: "800",
  },
  miniPlayerPlayButton: {
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 999,
    backgroundColor: "#1ed760",
    minWidth: 78,
    height: 36,
    paddingHorizontal: 16,
  },
  miniPlayerPlayText: {
    color: "#041208",
    fontSize: 13,
    fontWeight: "800",
    textTransform: "uppercase",
    letterSpacing: 0.3,
  },
  playerSheetSafeArea: {
    flex: 1,
    backgroundColor: "#121212",
    paddingHorizontal: 18,
    paddingTop: 14,
    paddingBottom: 26,
  },
  playerSheetTopRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
  },
  playerSheetTopIcon: {
    width: 34,
    height: 34,
    alignItems: "center",
    justifyContent: "center",
  },
  playerSheetTopIconText: {
    color: "#ffffff",
    fontSize: 18,
    fontWeight: "700",
  },
  playerSheetModeSwitch: {
    flexDirection: "row",
    alignItems: "center",
    gap: 2,
    borderRadius: 999,
    backgroundColor: "rgba(0,0,0,0.42)",
    padding: 3,
  },
  playerSheetModeTab: {
    borderRadius: 999,
    paddingHorizontal: 22,
    paddingVertical: 7,
  },
  playerSheetModeTabActive: {
    backgroundColor: "#111111",
  },
  playerSheetModeText: {
    color: "#f0d9d9",
    fontSize: 13,
    fontWeight: "600",
  },
  playerSheetModeTextActive: {
    color: "#ffffff",
    fontWeight: "700",
  },
  playerSheetHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 12,
  },
  playerSheetHeaderAction: {
    width: 36,
    height: 36,
    borderRadius: 999,
    alignItems: "center",
    justifyContent: "center",
  },
  playerSheetHeaderCopy: {
    flex: 1,
    alignItems: "center",
    minWidth: 0,
  },
  playerSheetHeaderEyebrow: {
    color: "#e4e7ea",
    fontSize: 10,
    fontWeight: "700",
    letterSpacing: 1.8,
  },
  playerSheetHeaderTitle: {
    marginTop: 4,
    color: "#ffffff",
    fontSize: 13,
    fontWeight: "700",
  },
  playerSheetHeaderSymbol: {
    color: "#f4f5f6",
    fontSize: 18,
    fontWeight: "700",
  },
  playerSheetClose: {
    color: "#f4f5f6",
    fontSize: 14,
    fontWeight: "700",
  },
  playerSheetArtwork: {
    width: "100%",
    aspectRatio: 1,
    alignSelf: "stretch",
    marginTop: 18,
    borderRadius: 18,
    backgroundColor: "#151515",
  },
  playerSheetFallback: {
    width: "100%",
    aspectRatio: 1,
    alignSelf: "stretch",
    marginTop: 18,
    borderRadius: 18,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#121212",
  },
  playerSheetFallbackText: {
    color: "#1ed760",
    fontSize: 24,
    fontWeight: "800",
    letterSpacing: 2,
  },
  playerSheetVideoWrap: {
    width: "100%",
    aspectRatio: 1,
    alignSelf: "stretch",
    marginTop: 18,
    borderRadius: 18,
    overflow: "hidden",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.08)",
    backgroundColor: "#000000",
  },
  playerSheetVideo: {
    flex: 1,
    backgroundColor: "#000000",
  },
  playerSheetTitle: {
    marginTop: 22,
    color: "#ffffff",
    fontSize: 28,
    lineHeight: 33,
    fontWeight: "800",
    letterSpacing: -0.9,
  },
  playerSheetArtist: {
    marginTop: 4,
    color: "#e7d4d4",
    fontSize: 23,
    fontWeight: "500",
  },
  playerSheetActionRow: {
    marginTop: 18,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
  },
  playerSheetActionChip: {
    flex: 1,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.12)",
    backgroundColor: "rgba(255,255,255,0.03)",
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 8,
  },
  playerSheetActionText: {
    color: "#f6eded",
    fontSize: 12,
    fontWeight: "600",
  },
  playerSheetTimeline: {
    marginTop: 14,
  },
  playerAssistRow: {
    marginTop: 8,
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  playerAssistText: {
    flex: 1,
    color: "#f6f7f9",
    fontSize: 11,
    lineHeight: 16,
  },
  playerAssistTextError: {
    color: "#ff9ba7",
  },
  playerAssistTextSuccess: {
    color: "#8df0b4",
  },
  playerSheetMetaRow: {
    marginTop: 18,
    flexDirection: "row",
    gap: 10,
  },
  playerSheetMetaCard: {
    flex: 1,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.08)",
    backgroundColor: "#151515",
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  playerSheetMetaLabel: {
    color: "#8c9096",
    fontSize: 11,
    fontWeight: "700",
    letterSpacing: 1,
    textTransform: "uppercase",
  },
  playerSheetMetaValue: {
    marginTop: 6,
    color: "#ffffff",
    fontSize: 14,
    fontWeight: "700",
  },
  playerSheetControls: {
    marginTop: 24,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
  },
  playerSheetSecondary: {
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 999,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.08)",
    backgroundColor: "#151515",
    width: 58,
    height: 58,
  },
  playerSheetSecondaryText: {
    color: "#f4f5f6",
    fontSize: 13,
    fontWeight: "800",
  },
  playerSheetPrimary: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 999,
    backgroundColor: "#1ed760",
    height: 64,
  },
  playerSheetPrimaryText: {
    color: "#041208",
    fontSize: 24,
    fontWeight: "800",
    lineHeight: 28,
  },
  playerSheetPrimaryIcon: {
    lineHeight: 28,
  },
  playerSheetTransportRow: {
    marginTop: 20,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  playerSheetTransportIcon: {
    width: 38,
    height: 38,
    alignItems: "center",
    justifyContent: "center",
  },
  playerSheetTransportIconText: {
    color: "#ffffff",
    fontSize: 20,
    fontWeight: "700",
  },
  playerSheetPlayButton: {
    width: 86,
    height: 86,
    borderRadius: 999,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#1db954",
  },
  playerSheetPlayButtonText: {
    color: "#041208",
    fontSize: 34,
    fontWeight: "800",
    marginLeft: 2,
  },
  playerSheetBottomTabs: {
    marginTop: 30,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 8,
  },
  playerSheetBottomTabText: {
    color: "rgba(255,255,255,0.82)",
    fontSize: 12,
    fontWeight: "700",
    letterSpacing: 0.8,
  },
  logCard: {
    marginTop: 14,
    borderRadius: 18,
    backgroundColor: "#131313",
    padding: 14,
    gap: 8,
  },
  logLine: {
    color: "#b8bbc0",
    fontSize: 12,
    lineHeight: 18,
  },
  modalSafeArea: {
    flex: 1,
    backgroundColor: "#050505",
    paddingHorizontal: 16,
    paddingTop: 12,
    paddingBottom: 20,
  },
  modalHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    gap: 12,
  },
  modalTitle: {
    marginTop: 8,
    color: "#ffffff",
    fontSize: 20,
    lineHeight: 26,
    fontWeight: "800",
  },
  modalMeta: {
    marginTop: 6,
    color: "#9ea0a6",
    fontSize: 14,
    lineHeight: 20,
  },
});
